language: ruby
cache: bundler
env:
  - DATABASE_ADAPTER=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace test
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:setup
services:
  - postgresql
dist: xenial
sudo: required
