defaults: &defaults
  max_export_records_count: 1000
  signin_url: /signin
  root_prefix: /liza
  start_year: 2021
  default_url_options: &default_url_options
    protocol: <%= ENV.fetch('HTTP_PROTOCOL', 'https') %>
    host: <%= ENV.fetch('LIZA_HOST', 'localhost') %>

  peatio_api_url: https://dev.bitzlato.bz/api/v2/peatio
  barong_api_url: https://dev.bitzlato.bz/api/v2/barong
  sidekiq_redis: 
    url: redis://localhost:6379/3
  cache_store:
    url: redis://localhost:6379/2
development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
