defaults: &defaults
  signin_url: /signin
  root_prefix: /liza
  start_year: 2021
  default_url_options: &default_url_options
    protocol: <%= ENV.fetch('HTTP_PROTOCOL', 'https') %>
    host: <%= ENV.fetch('LIZA_HOST', 'localhost') %>

development:
  <<: *defaults
